# Generated by Django 4.0.5 on 2022-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
